"use client";

import Link from "next/link";
import {useIdentity} from "@/components/identity-provider";
import {useScoutDashboard} from "@/components/use-scout-dashboard";

export function ScoutPortfolio(){
  const identity=useIdentity();
  const {dashboard,loading}=useScoutDashboard(identity.address);
  const positions=dashboard?.positions??[];
  const realizedRoi=dashboard?.realizedRoi;
  return <div className="standard-page"><div className="standard-heading"><div><p className="eyebrow">Conviction portfolio</p><h1>My positions</h1><p>{loading?"Loading confirmed positions…":"Every call, entry point, outcome, and reward in one onchain record."}</p></div><div className="portfolio-value"><span>Realized scout return</span><strong className={realizedRoi!==null&&realizedRoi!==undefined&&realizedRoi<0?"negative":""}>{realizedRoi===null||realizedRoi===undefined?"Pending":`${realizedRoi>=0?"+":""}${realizedRoi.toFixed(1)}%`}</strong></div></div><section className="portfolio-stats"><div><span>Signals backed</span><strong>{positions.filter(position=>position.market.status!=="settled").length}</strong></div><div><span>Conviction committed</span><strong>{(dashboard?.spent??0).toFixed(3)} MON</strong></div><div><span>Verified rewards</span><strong className="positive">{((dashboard?.claimed??0)+(dashboard?.withdrawnCredit??0)).toFixed(3)} MON</strong></div></section><div className="position-table"><div className="table-head"><span>Signal</span><span>Conviction rank</span><span>Your position</span><span>Outcome</span></div>{positions.map(position=><Link href={`/market/${position.market.id}`} className="position-row" key={position.market.id}><span><strong>{position.market.author.displayName}</strong><small>{position.market.text.slice(0,44)}…</small></span><span>#{position.market.rank}</span><span>{position.spent.toFixed(3)} MON</span><strong className={position.claimed>0?"positive":""}>{position.claimed>0?`+${position.claimed.toFixed(3)} MON`:position.market.status}</strong></Link>)}{!loading&&!positions.length&&<div className="empty-state wallet-empty"><strong>{identity.authenticated?"No positions yet":"Connect your wallet"}</strong><p>{identity.authenticated?"Your confirmed signal positions will be indexed here automatically.":"Connect through Privy to see your conviction, outcomes, and scout reputation."}</p><div><button className="primary-button" onClick={identity.authenticated?()=>{window.location.href="/discover"}:identity.login}>{identity.authenticated?"Open conviction feed":"Connect wallet"}</button><a className="secondary-button" href="https://faucet.monad.xyz/" target="_blank" rel="noreferrer">Get testnet MON ↗</a></div><small>{identity.gasSponsored?"Privy sponsors network gas; only the conviction amount leaves your wallet.":"Your wallet displays any network fee before you sign."}</small></div>}</div></div>;
}
