import Link from "next/link";
import type {Metadata} from "next";
import {ConvictionLens} from "@/components/market/conviction-lens";
import {convictionFixture} from "@/lib/conviction-fixture";
import {nansenFieldReport} from "@/lib/nansen-evidence";

export const metadata: Metadata = {title: "Nansen Conviction Lens", description: "Understand who backs a Farcaster signal through Envio scout conviction and Nansen wallet relationship evidence."};

export default function IntelligencePage() {
  return <div className="intelligence-page"><header className="intelligence-intro"><p className="eyebrow">Dibs × Nansen</p><h1>A crowd of wallets<br/>isn’t the whole story.</h1><p>Conviction Lens joins Envio’s stake ledger with Nansen’s wallet relationships. Before calling Dibs, see whether conviction is concentrated, inspect reported connections, and recognize where coverage ends.</p><Link className="primary-button" href="/discover">Inspect a real signal →</Link></header><div className="intelligence-steps"><article><span>01 · Envio</span><h2>Who put conviction behind it?</h2><p>Read genuine scout addresses and exact wei stakes from the indexed market. Exclude protocol seed from concentration.</p></article><article><span>02 · Nansen</span><h2>What connects the backers?</h2><p>Query the related-wallets endpoint for up to eight early scouts on the selected Monad, Base or Ethereum dataset.</p></article><article><span>03 · Your decision</span><h2>Understand before committing.</h2><p>Inspect the relationship map, transactions and coverage. Context informs you; it never rewrites settlement rules.</p></article></div><ConvictionLens marketId={nansenFieldReport.marketId} initialReport={nansenFieldReport} historicalSnapshot/><section className="intelligence-notes"><h2>How returned relationships would change the picture</h2><p>The genuine capture above returned no relationship records. The separate example below illustrates connections with synthetic data; it is not a substitute for that result.</p></section><ConvictionLens marketId="example" initialReport={convictionFixture}/><section className="intelligence-notes"><h2>Explicit data boundaries</h2><p>The teaching example above is synthetic, not live API evidence. The recorded market snapshot is genuine but historical and operator-captured. Fresh scans live on indexed market pages, require a verified Privy session with linked Farcaster, and use a server-only Nansen API key. A missing API key never enables fixture results on a real market.</p><p>Nansen’s external network context is not assumed to include Dibs’ Monad testnet transactions. Missing links do not prove independence; returned links do not prove shared ownership. No prohibited label or Smart Money data is redistributed.</p><a href="https://docs.nansen.ai/api/profiler/address-related-wallets" target="_blank" rel="noreferrer">Integrated endpoint documentation ↗</a><a href="https://docs.nansen.ai/guides/redistribution-guide" target="_blank" rel="noreferrer">Nansen attribution and redistribution rules ↗</a></section></div>;
}
